travis:
  secure:
    BINSTAR_TOKEN: M3wjhY6kvsfjnkqVZxBMg+uNx9pePsYQw/Zxa32oNFE5DWogvxWndtJisrUtFdAy8ztkcHY7DWG12MD4J2Nb31Tcn0p1/euep0tf/4J4R2y6kv+eZK8Zalc9+JVThoC8d5bS3++c173YDyB4Ilva0h/Zg7clSx8GSeGkwEcm0TjwhGIYKPf4xAoUUL+cvpXk5G5enLynSItpmGfR3PDreij1VTcRLG0OBN59QPFc8UfWA8lsL/n/XEXTkRHpgR/nzQXsjOtYu8nUFF5N4onx/5ZTuwbid8gkGyAJIn/RlnwqcE2rTLk67ZzWFvPli3nXRTJALu39k6IRV9RL+Za5OnrR2+Utox/QI4AAc1sBD9hPiBSEL8EzyTcOZkCPmPs5TW0gDtuCie9QpPWaVSSlUrfGNGIxRKP+UUWH3uZDtSxMTNsanH/ZAHxrc2eYHLH6Ey9szV/2PtAO3FqNbHP2iXFaGilZ3lo8MpbbEDzaeHyGEbgbZ35KVhUZXbz9y3PsKIVdYY7c6OnQ3xdOV8K5tQuBz0b8pkWqwL1qsOcHok/re/FSY2AtFy4vNLUP+jq58mQNUoQjLN4SXjyfHuH5GEhlcbWQniMcNAlz0B6oy6N+HxOsEDsQGkrCSxMBvJw65Gnat3bkglHmbkf1bODeRRtxLo7QyWpD9i9JGWPxo/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
